version: "3.8"

services:
  web:
    depends_on:
      - postgres
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_NAME=ecommerce
      - DB_USERNAME=local_user
      - DB_PASSWORD=local_password
      - JWT_SECRET=mysecretsecret
      - REDIS_URL=redis://redis:6379
    deploy:
      resources:
        limits:
          cpus: "0.256"
          memory: 512M

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=local_user
      - POSTGRES_PASSWORD=local_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

  # datadog:
  #   image: datadog/agent:latest
  #   environment:
  #     - DD_API_KEY=${DATADOG_API_KEY}
  #     - DD_SITE=us5.datadoghq.com
  #     - DD_APM_ENABLED=true
  #     - DD_LOGS_ENABLED=true
  #     - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - /proc/:/host/proc/:ro
  #     - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
